server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/patients/**

        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/doctors/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
